### PR TITLE
Create rearranging-services.md

### PR DESCRIPTION
**Pull request by AuthorShin**
### Category
Documentation

### Overview
Adding the page for DND and it's needed delay to docs.

### Issue Number _(if applicable)_
[#413](https://github.com/ajnart/homarr/issues/413)

### CODE REVIEW

**Comment by ajnart** [comment]
Could you add a gif and add the mention that for now you cannot rearrange categories ? Thank you for the PR 🙏🏻
Will merge after the changes

**Review by ajnart — CHANGES_REQUESTED** [review]
Please add a gif and the mention that you can reorder categories for now.

**Comment by AuthorShin** [comment]
I think this will do it, what do you think?
`Keep in mind that currently you can only arrange them within their current category (only for now).`

**Comment by AuthorShin** [comment]
@ajnart Is it okay?

**Comment by ajnart** [comment]
> @ajnart Is it okay?

sorry I didn't see.

**Comment by ajnart** [comment]
> I think this will do it, what do you think?
> `Keep in mind that currently you can only arrange them within their current category (only for now).`

Yeah this works

**Review by ajnart — APPROVED** [review]

**Comment by AuthorShin** [comment]
@ajnart Care to merge :)

**Comment by ajnart** [comment]
omg so sorry i forgot 💀

**Pull request merged**
